import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/global.css";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lista de Espaçonaves",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <div className={`${geistSans.variable} ${geistMono.variable} antialiased bg-blue-50 dark:bg-gray-950 text-gray-900 dark:text-gray-50 h-dvh`}>
          <nav className="flex justify-between px-10 py-3">
            <h1 className="p-2 bg-blue-950 rounded-full font-bold text-gray-50">CoddeX Spaceships</h1>
            <div className="flex gap-2">
              <Link className="border-b hover:bg-blue-500 hover:text-white px-1 rounded-sm items-center flex" href={`/`}>Home</Link>
              <Link className="border-b hover:bg-blue-500 hover:text-white px-1 rounded-sm items-center flex" href={`/models`}>Models</Link>
            </div>
          </nav>
          {children}
        </div>
        <footer className="py-3 bg-blue-950 text-center text-[10pt] text-white">
          CoddeX Developer {`${new Date().getFullYear()}`}
        </footer>
      </body>
    </html>
  );
}
